"""initial: create all tables

Revision ID: e632efb46135
Revises: 
Create Date: 2026-07-06 20:28:27.667745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e632efb46135'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_username'), 'admin_user', ['username'], unique=True)
    op.create_table('ca_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ca_name', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('province', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('keystore_path', sa.Text(), nullable=True),
    sa.Column('signature_algorithm', sa.String(length=64), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('is_initialized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crl_publish',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crl_number', sa.Integer(), nullable=False),
    sa.Column('issuer_dn', sa.String(length=512), nullable=False),
    sa.Column('this_update', sa.DateTime(), nullable=False),
    sa.Column('next_update', sa.DateTime(), nullable=False),
    sa.Column('signature_algorithm', sa.String(length=64), nullable=False),
    sa.Column('crl_pem', sa.Text(), nullable=False),
    sa.Column('revoked_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crl_publish_crl_number'), 'crl_publish', ['crl_number'], unique=False)
    op.create_table('crl_revocation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cert_serial_number', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crl_revocation_cert_serial_number'), 'crl_revocation', ['cert_serial_number'], unique=True)
    op.create_table('root_cert',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('subject_dn', sa.String(length=512), nullable=False),
    sa.Column('issuer_dn', sa.String(length=512), nullable=False),
    sa.Column('signature_algorithm', sa.String(length=64), nullable=False),
    sa.Column('not_before', sa.DateTime(), nullable=False),
    sa.Column('not_after', sa.DateTime(), nullable=False),
    sa.Column('cert_pem', sa.Text(), nullable=False),
    sa.Column('key_pem', sa.Text(), nullable=False),
    sa.Column('key_size', sa.Integer(), nullable=False),
    sa.Column('subject_key_identifier', sa.String(length=128), nullable=True),
    sa.Column('authority_key_identifier', sa.String(length=128), nullable=True),
    sa.Column('basic_constraints', sa.String(length=128), nullable=True),
    sa.Column('key_usage', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_root_cert_serial_number'), 'root_cert', ['serial_number'], unique=True)
    op.create_table('token_blacklist',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_jti', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_token_jti'), 'token_blacklist', ['token_jti'], unique=True)
    op.create_table('user_cert',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('cert_type', sa.String(length=16), nullable=False),
    sa.Column('subject_dn', sa.String(length=512), nullable=False),
    sa.Column('issuer_dn', sa.String(length=512), nullable=False),
    sa.Column('root_cert_serial', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('signature_algorithm', sa.String(length=64), nullable=False),
    sa.Column('not_before', sa.DateTime(), nullable=False),
    sa.Column('not_after', sa.DateTime(), nullable=False),
    sa.Column('cert_pem', sa.Text(), nullable=False),
    sa.Column('key_pem', sa.Text(), nullable=True),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('key_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cert_serial_number'), 'user_cert', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cert_serial_number'), table_name='user_cert')
    op.drop_table('user_cert')
    op.drop_index(op.f('ix_token_blacklist_token_jti'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_root_cert_serial_number'), table_name='root_cert')
    op.drop_table('root_cert')
    op.drop_index(op.f('ix_crl_revocation_cert_serial_number'), table_name='crl_revocation')
    op.drop_table('crl_revocation')
    op.drop_index(op.f('ix_crl_publish_crl_number'), table_name='crl_publish')
    op.drop_table('crl_publish')
    op.drop_table('ca_config')
    op.drop_index(op.f('ix_admin_user_username'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
